### PR TITLE
Reimplement the tool from scratch

### PR DESCRIPTION
**Pull request by v--**
* Avoid external binaries
  * Rely on python-djvulibre for extracting data from source files
  * Use Pillow to decode images from djvulibre and save them as compressed PDF files
  * Use fpdf2 to produce a PDF file containing the corresponding text layers
  * Use pdfrw to produce PDF files containing the above images with invisible text overlays and document outlines

* Use multiprocessing for concurrency

* Add verbose logging

* Add sanity tests with fixtures

### CODE REVIEW

**Comment by v--** [comment]
I just found out that some of the produced files are substantially larger than  before. I have some ideas. Gonna take a look at it later. There are going to be more changes.

**Comment by kcroker** [comment]
lol I've officially turned into a project maintainer ;)  Let me know when you're satisfied with the file sizes and I'll pull it and test it here

**Comment by v--** [comment]
I believe that the resulting PDF files now have satisfactory compression. Feel free to review, test and comment.

PS: The recent force-pushes were done while adjusting a GitHub Actions workflow.

**Comment by kcroker** [comment]
I've cloned, installed poetry, installed system-wide djvulibre, and verified a multitprocess conversion that preserves the OCR.  File size looks as expected.  I don't have any DJVU at the moment with an non-trivial index / bookmarking.  Have you tested these aspects of the conversion?  If not, I can generate one and verify.

**Comment by v--** [comment]
Are the books [here](https://ivasilev.net/files/Scanned) complicated enough? If so, I can convert them successfully from their DjVu sources (but those uploaded are old).

I tried writing a test for outline transformation, but it turned out really awkward so I didn't commit it.

**Comment by kcroker** [comment]
Sorry this took me so long to pivot back to.  I am merging now.  If issues come up, we can get it straightened out with the files which cause the problems.

**Pull request merged**
